version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./init:/docker-entrypoint-initdb.d
#    networks:
#      - my_network

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
#    networks:
#      - my_network

#  frontend:
#    build:
#      context: ./frontend
#    ports:
#      - "8080:8080"
#    depends_on:
#      - backend
#    networks:
#      - my_network

#networks:
#  my_network: