version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres

#  frontend:
#    build:
#      context: ./frontend
#    ports:
#      - "8080:8080"
#    depends_on:
#      - backend